
all:
	C:/Users/avik/Documents/arduino-1.6.1/arduino_debug --upload --board koduino:stm32:f303v:hse=8m,bootloader=stm32loader --port COM7 C:/Users/avik/Documents/mainboard-libraries/minitaur_gaits/minitaur_gaits.ino

# # # Mainboard2
# # VARIANT = f40_41x
# # UPLOAD_METHOD = SERIAL
# # HSE_VALUE = 16000000UL
# # # dtr_rts or rts_trpl_inv
# # UPLOAD_ENTRY = rts_trpl_inv
# # UPLOAD_BAUD = 115200
# # SECTOR_ERASE = 1

# # mblc0.4
# VARIANT = f303v
# UPLOAD_METHOD = SERIAL
# UPLOAD_ENTRY = mblc
# UPLOAD_PORT = COM4
# HSE_VALUE = 8000000UL
# KODUINO_ISRS = INLINE
# # 72MHz
# CLKSRC = HSE_8M
# # overclocked to 112 MHz
# # CLKSRC = HSE_8M_OC112
# EEP_START = 0x0800F000
# # EEP_LEN = 0
# MAX_PROGRAM_SIZE = 61440

# # # bllc0.6
# # VARIANT = f301
# # #VARIANT = f37x
# # UPLOAD_METHOD = SERIAL
# # HSE_VALUE = 16000000UL
# # # dtr_rts or rts_trpl_inv
# # UPLOAD_ENTRY = none
# # SECTOR_ERASE = 1
# # MAX_PROGRAM_SIZE = 28672
# # EEP_START = 0x08007000
# # CLKSRC = HSE_8M



# LIBRARIES = Dxl MotorController DxlMotor SPI IMU Eigen OpenLog Robot
# # LIBRARIES = MotorController SPI IMU Eigen OpenLog Robot

# include $(KODUINO_DIR)/project.mk
