
# ARDUINO UPLOAD COMMENT OUT IF USING MAKE BUILD
all:
	arduino_debug --verbose-upload --upload --board koduino:stm32:f303v:hse=8m,bootloader=stm32loader --port COM5 "C:\Users\avik\Documents\inolibs\mblc0.5_template\mblc0.5_template.ino"

# MAKEFILE UPLOAD
# # mblc0.5
# VARIANT = f303v
# UPLOAD_METHOD = SERIAL
# UPLOAD_ENTRY = mblc
# # UPLOAD_PORT = COM4
# HSE_VALUE = 8000000UL
# KODUINO_ISRS = INLINE
# # 72MHz
# CLKSRC = HSE_8M
# # overclocked to 112 MHz
# # CLKSRC = HSE_8M_OC112

# # Don't save EEPROM
# EEP_START = 0x0800F000
# EEP_LEN = 0
# # 256kB
# MAX_PROGRAM_SIZE = 262144

# LIBRARIES = IMU SPI Eigen OpenLog MotorController

# include $(KODUINO_DIR)/project.mk